{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "fusion-gateway.fullname" . }}
  labels:
    {{- include "fusion-gateway.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "fusion-gateway.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - port: {{ .Values.service.port }}
          protocol: TCP
    {{- range .Values.networkPolicy.ingressFrom }}
    - from:
        {{- toYaml . | nindent 8 }}
      ports:
        - port: {{ $.Values.service.port }}
          protocol: TCP
    {{- end }}
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - to:
        - namespaceSelector: {}
{{- end }}
