apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fusion-gateway.fullname" . }}-secrets
  labels:
    {{- include "fusion-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  master_key: {{ .Values.secrets.master_key | default "CHANGE_ME" | quote }}
