apiVersion: v1
kind: Service
metadata:
  name: {{ include "fusion-gateway.fullname" . }}
  labels:
    {{- include "fusion-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "fusion-gateway.selectorLabels" . | nindent 4 }}
