apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fusion-gateway
  namespace: fusion-gateway
spec:
  podSelector:
    matchLabels:
      app: fusion-gateway
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: fusion-gateway
      ports:
        - port: 8100
          protocol: TCP
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - port: 8100
          protocol: TCP
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - to:
        - namespaceSelector: {}
