apiVersion: v1
kind: Service
metadata:
  name: fusion-gateway
  namespace: fusion-gateway
  labels:
    app: fusion-gateway
spec:
  type: ClusterIP
  ports:
    - port: 11432
      targetPort: 11432
      protocol: TCP
  selector:
    app: fusion-gateway
