// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.0
// source: internal/identity/pb/identity.proto

package identityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthErrorCode int32

const (
	AuthErrorCode_AUTH_ERROR_CODE_UNSPECIFIED AuthErrorCode = 0
	AuthErrorCode_INVALID_API_KEY             AuthErrorCode = 1
	AuthErrorCode_TENANT_DISABLED             AuthErrorCode = 2
	AuthErrorCode_MODULE_UNAUTHORIZED         AuthErrorCode = 3
	AuthErrorCode_MODEL_UNAUTHORIZED          AuthErrorCode = 4
	AuthErrorCode_CONCURRENCY_LIMIT_EXCEEDED  AuthErrorCode = 5
	AuthErrorCode_DAILY_QUOTA_EXCEEDED        AuthErrorCode = 6
	AuthErrorCode_RATE_LIMIT_EXCEEDED         AuthErrorCode = 7
)

// Enum value maps for AuthErrorCode.
var (
	AuthErrorCode_name = map[int32]string{
		0: "AUTH_ERROR_CODE_UNSPECIFIED",
		1: "INVALID_API_KEY",
		2: "TENANT_DISABLED",
		3: "MODULE_UNAUTHORIZED",
		4: "MODEL_UNAUTHORIZED",
		5: "CONCURRENCY_LIMIT_EXCEEDED",
		6: "DAILY_QUOTA_EXCEEDED",
		7: "RATE_LIMIT_EXCEEDED",
	}
	AuthErrorCode_value = map[string]int32{
		"AUTH_ERROR_CODE_UNSPECIFIED": 0,
		"INVALID_API_KEY":             1,
		"TENANT_DISABLED":             2,
		"MODULE_UNAUTHORIZED":         3,
		"MODEL_UNAUTHORIZED":          4,
		"CONCURRENCY_LIMIT_EXCEEDED":  5,
		"DAILY_QUOTA_EXCEEDED":        6,
		"RATE_LIMIT_EXCEEDED":         7,
	}
)

func (x AuthErrorCode) Enum() *AuthErrorCode {
	p := new(AuthErrorCode)
	*p = x
	return p
}

func (x AuthErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_identity_pb_identity_proto_enumTypes[0].Descriptor()
}

func (AuthErrorCode) Type() protoreflect.EnumType {
	return &file_internal_identity_pb_identity_proto_enumTypes[0]
}

func (x AuthErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthErrorCode.Descriptor instead.
func (AuthErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_internal_identity_pb_identity_proto_rawDescGZIP(), []int{0}
}

type PriorityLevel int32

const (
	PriorityLevel_PRIORITY_LEVEL_UNSPECIFIED PriorityLevel = 0
	PriorityLevel_PRIORITY_LOW               PriorityLevel = 1
	PriorityLevel_PRIORITY_NORMAL            PriorityLevel = 2
	PriorityLevel_PRIORITY_HIGH              PriorityLevel = 3
)

// Enum value maps for PriorityLevel.
var (
	PriorityLevel_name = map[int32]string{
		0: "PRIORITY_LEVEL_UNSPECIFIED",
		1: "PRIORITY_LOW",
		2: "PRIORITY_NORMAL",
		3: "PRIORITY_HIGH",
	}
	PriorityLevel_value = map[string]int32{
		"PRIORITY_LEVEL_UNSPECIFIED": 0,
		"PRIORITY_LOW":               1,
		"PRIORITY_NORMAL":            2,
		"PRIORITY_HIGH":              3,
	}
)

func (x PriorityLevel) Enum() *PriorityLevel {
	p := new(PriorityLevel)
	*p = x
	return p
}

func (x PriorityLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PriorityLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_identity_pb_identity_proto_enumTypes[1].Descriptor()
}

func (PriorityLevel) Type() protoreflect.EnumType {
	return &file_internal_identity_pb_identity_proto_enumTypes[1]
}

func (x PriorityLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PriorityLevel.Descriptor instead.
func (PriorityLevel) EnumDescriptor() ([]byte, []int) {
	return file_internal_identity_pb_identity_proto_rawDescGZIP(), []int{1}
}

type InferenceStatus int32

const (
	InferenceStatus_INFERENCE_STATUS_UNSPECIFIED InferenceStatus = 0
	InferenceStatus_SUCCESS                      InferenceStatus = 1
	InferenceStatus_CANCELED                     InferenceStatus = 2
	InferenceStatus_FAILED                       InferenceStatus = 3
)

// Enum value maps for InferenceStatus.
var (
	InferenceStatus_name = map[int32]string{
		0: "INFERENCE_STATUS_UNSPECIFIED",
		1: "SUCCESS",
		2: "CANCELED",
		3: "FAILED",
	}
	InferenceStatus_value = map[string]int32{
		"INFERENCE_STATUS_UNSPECIFIED": 0,
		"SUCCESS":                      1,
		"CANCELED":                     2,
		"FAILED":                       3,
	}
)

func (x InferenceStatus) Enum() *InferenceStatus {
	p := new(InferenceStatus)
	*p = x
	return p
}

func (x InferenceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InferenceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_identity_pb_identity_proto_enumTypes[2].Descriptor()
}

func (InferenceStatus) Type() protoreflect.EnumType {
	return &file_internal_identity_pb_identity_proto_enumTypes[2]
}

func (x InferenceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InferenceStatus.Descriptor instead.
func (InferenceStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_identity_pb_identity_proto_rawDescGZIP(), []int{2}
}

type AuthorizeAndAcquireRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	TargetModule  string                 `protobuf:"bytes,2,opt,name=target_module,json=targetModule,proto3" json:"target_module,omitempty"`
	TargetModel   string                 `protobuf:"bytes,3,opt,name=target_model,json=targetModel,proto3" json:"target_model,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ClientIp      string                 `protobuf:"bytes,5,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	TenantId      string                 `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeAndAcquireRequest) Reset() {
	*x = AuthorizeAndAcquireRequest{}
	mi := &file_internal_identity_pb_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeAndAcquireRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeAndAcquireRequest) ProtoMessage() {}

func (x *AuthorizeAndAcquireRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_identity_pb_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeAndAcquireRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeAndAcquireRequest) Descriptor() ([]byte, []int) {
	return file_internal_identity_pb_identity_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizeAndAcquireRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *AuthorizeAndAcquireRequest) GetTargetModule() string {
	if x != nil {
		return x.TargetModule
	}
	return ""
}

func (x *AuthorizeAndAcquireRequest) GetTargetModel() string {
	if x != nil {
		return x.TargetModel
	}
	return ""
}

func (x *AuthorizeAndAcquireRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AuthorizeAndAcquireRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *AuthorizeAndAcquireRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type TenantContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TenantName    string                 `protobuf:"bytes,2,opt,name=tenant_name,json=tenantName,proto3" json:"tenant_name,omitempty"`
	Tier          string                 `protobuf:"bytes,3,opt,name=tier,proto3" json:"tier,omitempty"`
	Priority      PriorityLevel          `protobuf:"varint,4,opt,name=priority,proto3,enum=fusion.identity.v1.PriorityLevel" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantContext) Reset() {
	*x = TenantContext{}
	mi := &file_internal_identity_pb_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantContext) ProtoMessage() {}

func (x *TenantContext) ProtoReflect() protoreflect.Message {
	mi := &file_internal_identity_pb_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantContext.ProtoReflect.Descriptor instead.
func (*TenantContext) Descriptor() ([]byte, []int) {
	return file_internal_identity_pb_identity_proto_rawDescGZIP(), []int{1}
}

func (x *TenantContext) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TenantContext) GetTenantName() string {
	if x != nil {
		return x.TenantName
	}
	return ""
}

func (x *TenantContext) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *TenantContext) GetPriority() PriorityLevel {
	if x != nil {
		return x.Priority
	}
	return PriorityLevel_PRIORITY_LEVEL_UNSPECIFIED
}

type AuthorizeAndAcquireResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IsAllowed        bool                   `protobuf:"varint,1,opt,name=is_allowed,json=isAllowed,proto3" json:"is_allowed,omitempty"`
	ErrorCode        AuthErrorCode          `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3,enum=fusion.identity.v1.AuthErrorCode" json:"error_code,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	TenantContext    *TenantContext         `protobuf:"bytes,4,opt,name=tenant_context,json=tenantContext,proto3" json:"tenant_context,omitempty"`
	LeaseId          string                 `protobuf:"bytes,5,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	MaxAllowedTokens int32                  `protobuf:"varint,6,opt,name=max_allowed_tokens,json=maxAllowedTokens,proto3" json:"max_allowed_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthorizeAndAcquireResponse) Reset() {
	*x = AuthorizeAndAcquireResponse{}
	mi := &file_internal_identity_pb_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeAndAcquireResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeAndAcquireResponse) ProtoMessage() {}

func (x *AuthorizeAndAcquireResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_identity_pb_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeAndAcquireResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeAndAcquireResponse) Descriptor() ([]byte, []int) {
	return file_internal_identity_pb_identity_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorizeAndAcquireResponse) GetIsAllowed() bool {
	if x != nil {
		return x.IsAllowed
	}
	return false
}

func (x *AuthorizeAndAcquireResponse) GetErrorCode() AuthErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return AuthErrorCode_AUTH_ERROR_CODE_UNSPECIFIED
}

func (x *AuthorizeAndAcquireResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *AuthorizeAndAcquireResponse) GetTenantContext() *TenantContext {
	if x != nil {
		return x.TenantContext
	}
	return nil
}

func (x *AuthorizeAndAcquireResponse) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *AuthorizeAndAcquireResponse) GetMaxAllowedTokens() int32 {
	if x != nil {
		return x.MaxAllowedTokens
	}
	return 0
}

type ReleaseLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseLeaseRequest) Reset() {
	*x = ReleaseLeaseRequest{}
	mi := &file_internal_identity_pb_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseLeaseRequest) ProtoMessage() {}

func (x *ReleaseLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_identity_pb_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseLeaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseLeaseRequest) Descriptor() ([]byte, []int) {
	return file_internal_identity_pb_identity_proto_rawDescGZIP(), []int{3}
}

func (x *ReleaseLeaseRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *ReleaseLeaseRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ReleaseLeaseRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReleaseLeaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseLeaseResponse) Reset() {
	*x = ReleaseLeaseResponse{}
	mi := &file_internal_identity_pb_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseLeaseResponse) ProtoMessage() {}

func (x *ReleaseLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_identity_pb_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseLeaseResponse.ProtoReflect.Descriptor instead.
func (*ReleaseLeaseResponse) Descriptor() ([]byte, []int) {
	return file_internal_identity_pb_identity_proto_rawDescGZIP(), []int{4}
}

func (x *ReleaseLeaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ReportUsageRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LeaseId          string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	TenantId         string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ModelName        string                 `protobuf:"bytes,3,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	PromptTokens     int32                  `protobuf:"varint,4,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,5,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	ExecutionTimeMs  int64                  `protobuf:"varint,6,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	Status           InferenceStatus        `protobuf:"varint,7,opt,name=status,proto3,enum=fusion.identity.v1.InferenceStatus" json:"status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReportUsageRequest) Reset() {
	*x = ReportUsageRequest{}
	mi := &file_internal_identity_pb_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportUsageRequest) ProtoMessage() {}

func (x *ReportUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_identity_pb_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportUsageRequest.ProtoReflect.Descriptor instead.
func (*ReportUsageRequest) Descriptor() ([]byte, []int) {
	return file_internal_identity_pb_identity_proto_rawDescGZIP(), []int{5}
}

func (x *ReportUsageRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *ReportUsageRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ReportUsageRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ReportUsageRequest) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *ReportUsageRequest) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *ReportUsageRequest) GetExecutionTimeMs() int64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

func (x *ReportUsageRequest) GetStatus() InferenceStatus {
	if x != nil {
		return x.Status
	}
	return InferenceStatus_INFERENCE_STATUS_UNSPECIFIED
}

type ReportUsageResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Success             bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RemainingDailyQuota int64                  `protobuf:"varint,2,opt,name=remaining_daily_quota,json=remainingDailyQuota,proto3" json:"remaining_daily_quota,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ReportUsageResponse) Reset() {
	*x = ReportUsageResponse{}
	mi := &file_internal_identity_pb_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportUsageResponse) ProtoMessage() {}

func (x *ReportUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_identity_pb_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportUsageResponse.ProtoReflect.Descriptor instead.
func (*ReportUsageResponse) Descriptor() ([]byte, []int) {
	return file_internal_identity_pb_identity_proto_rawDescGZIP(), []int{6}
}

func (x *ReportUsageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportUsageResponse) GetRemainingDailyQuota() int64 {
	if x != nil {
		return x.RemainingDailyQuota
	}
	return 0
}

var File_internal_identity_pb_identity_proto protoreflect.FileDescriptor

const file_internal_identity_pb_identity_proto_rawDesc = "" +
	"\n" +
	"#internal/identity/pb/identity.proto\x12\x12fusion.identity.v1\"\xd6\x01\n" +
	"\x1aAuthorizeAndAcquireRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12#\n" +
	"\rtarget_module\x18\x02 \x01(\tR\ftargetModule\x12!\n" +
	"\ftarget_model\x18\x03 \x01(\tR\vtargetModel\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12\x1b\n" +
	"\tclient_ip\x18\x05 \x01(\tR\bclientIp\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\tR\btenantId\"\xa0\x01\n" +
	"\rTenantContext\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vtenant_name\x18\x02 \x01(\tR\n" +
	"tenantName\x12\x12\n" +
	"\x04tier\x18\x03 \x01(\tR\x04tier\x12=\n" +
	"\bpriority\x18\x04 \x01(\x0e2!.fusion.identity.v1.PriorityLevelR\bpriority\"\xb6\x02\n" +
	"\x1bAuthorizeAndAcquireResponse\x12\x1d\n" +
	"\n" +
	"is_allowed\x18\x01 \x01(\bR\tisAllowed\x12@\n" +
	"\n" +
	"error_code\x18\x02 \x01(\x0e2!.fusion.identity.v1.AuthErrorCodeR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12H\n" +
	"\x0etenant_context\x18\x04 \x01(\v2!.fusion.identity.v1.TenantContextR\rtenantContext\x12\x19\n" +
	"\blease_id\x18\x05 \x01(\tR\aleaseId\x12,\n" +
	"\x12max_allowed_tokens\x18\x06 \x01(\x05R\x10maxAllowedTokens\"e\n" +
	"\x13ReleaseLeaseRequest\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"0\n" +
	"\x14ReleaseLeaseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa6\x02\n" +
	"\x12ReportUsageRequest\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"model_name\x18\x03 \x01(\tR\tmodelName\x12#\n" +
	"\rprompt_tokens\x18\x04 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x05 \x01(\x05R\x10completionTokens\x12*\n" +
	"\x11execution_time_ms\x18\x06 \x01(\x03R\x0fexecutionTimeMs\x12;\n" +
	"\x06status\x18\a \x01(\x0e2#.fusion.identity.v1.InferenceStatusR\x06status\"c\n" +
	"\x13ReportUsageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x122\n" +
	"\x15remaining_daily_quota\x18\x02 \x01(\x03R\x13remainingDailyQuota*\xde\x01\n" +
	"\rAuthErrorCode\x12\x1f\n" +
	"\x1bAUTH_ERROR_CODE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fINVALID_API_KEY\x10\x01\x12\x13\n" +
	"\x0fTENANT_DISABLED\x10\x02\x12\x17\n" +
	"\x13MODULE_UNAUTHORIZED\x10\x03\x12\x16\n" +
	"\x12MODEL_UNAUTHORIZED\x10\x04\x12\x1e\n" +
	"\x1aCONCURRENCY_LIMIT_EXCEEDED\x10\x05\x12\x18\n" +
	"\x14DAILY_QUOTA_EXCEEDED\x10\x06\x12\x17\n" +
	"\x13RATE_LIMIT_EXCEEDED\x10\a*i\n" +
	"\rPriorityLevel\x12\x1e\n" +
	"\x1aPRIORITY_LEVEL_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x01\x12\x13\n" +
	"\x0fPRIORITY_NORMAL\x10\x02\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x03*Z\n" +
	"\x0fInferenceStatus\x12 \n" +
	"\x1cINFERENCE_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\f\n" +
	"\bCANCELED\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x032\xcc\x02\n" +
	"\x0fIdentityService\x12v\n" +
	"\x13AuthorizeAndAcquire\x12..fusion.identity.v1.AuthorizeAndAcquireRequest\x1a/.fusion.identity.v1.AuthorizeAndAcquireResponse\x12a\n" +
	"\fReleaseLease\x12'.fusion.identity.v1.ReleaseLeaseRequest\x1a(.fusion.identity.v1.ReleaseLeaseResponse\x12^\n" +
	"\vReportUsage\x12&.fusion.identity.v1.ReportUsageRequest\x1a'.fusion.identity.v1.ReportUsageResponseB\x1fZ\x1dfusion/identity/v1;identityv1b\x06proto3"

var (
	file_internal_identity_pb_identity_proto_rawDescOnce sync.Once
	file_internal_identity_pb_identity_proto_rawDescData []byte
)

func file_internal_identity_pb_identity_proto_rawDescGZIP() []byte {
	file_internal_identity_pb_identity_proto_rawDescOnce.Do(func() {
		file_internal_identity_pb_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_identity_pb_identity_proto_rawDesc), len(file_internal_identity_pb_identity_proto_rawDesc)))
	})
	return file_internal_identity_pb_identity_proto_rawDescData
}

var file_internal_identity_pb_identity_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_internal_identity_pb_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_identity_pb_identity_proto_goTypes = []any{
	(AuthErrorCode)(0),                  // 0: fusion.identity.v1.AuthErrorCode
	(PriorityLevel)(0),                  // 1: fusion.identity.v1.PriorityLevel
	(InferenceStatus)(0),                // 2: fusion.identity.v1.InferenceStatus
	(*AuthorizeAndAcquireRequest)(nil),  // 3: fusion.identity.v1.AuthorizeAndAcquireRequest
	(*TenantContext)(nil),               // 4: fusion.identity.v1.TenantContext
	(*AuthorizeAndAcquireResponse)(nil), // 5: fusion.identity.v1.AuthorizeAndAcquireResponse
	(*ReleaseLeaseRequest)(nil),         // 6: fusion.identity.v1.ReleaseLeaseRequest
	(*ReleaseLeaseResponse)(nil),        // 7: fusion.identity.v1.ReleaseLeaseResponse
	(*ReportUsageRequest)(nil),          // 8: fusion.identity.v1.ReportUsageRequest
	(*ReportUsageResponse)(nil),         // 9: fusion.identity.v1.ReportUsageResponse
}
var file_internal_identity_pb_identity_proto_depIdxs = []int32{
	1, // 0: fusion.identity.v1.TenantContext.priority:type_name -> fusion.identity.v1.PriorityLevel
	0, // 1: fusion.identity.v1.AuthorizeAndAcquireResponse.error_code:type_name -> fusion.identity.v1.AuthErrorCode
	4, // 2: fusion.identity.v1.AuthorizeAndAcquireResponse.tenant_context:type_name -> fusion.identity.v1.TenantContext
	2, // 3: fusion.identity.v1.ReportUsageRequest.status:type_name -> fusion.identity.v1.InferenceStatus
	3, // 4: fusion.identity.v1.IdentityService.AuthorizeAndAcquire:input_type -> fusion.identity.v1.AuthorizeAndAcquireRequest
	6, // 5: fusion.identity.v1.IdentityService.ReleaseLease:input_type -> fusion.identity.v1.ReleaseLeaseRequest
	8, // 6: fusion.identity.v1.IdentityService.ReportUsage:input_type -> fusion.identity.v1.ReportUsageRequest
	5, // 7: fusion.identity.v1.IdentityService.AuthorizeAndAcquire:output_type -> fusion.identity.v1.AuthorizeAndAcquireResponse
	7, // 8: fusion.identity.v1.IdentityService.ReleaseLease:output_type -> fusion.identity.v1.ReleaseLeaseResponse
	9, // 9: fusion.identity.v1.IdentityService.ReportUsage:output_type -> fusion.identity.v1.ReportUsageResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_identity_pb_identity_proto_init() }
func file_internal_identity_pb_identity_proto_init() {
	if File_internal_identity_pb_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_identity_pb_identity_proto_rawDesc), len(file_internal_identity_pb_identity_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_identity_pb_identity_proto_goTypes,
		DependencyIndexes: file_internal_identity_pb_identity_proto_depIdxs,
		EnumInfos:         file_internal_identity_pb_identity_proto_enumTypes,
		MessageInfos:      file_internal_identity_pb_identity_proto_msgTypes,
	}.Build()
	File_internal_identity_pb_identity_proto = out.File
	file_internal_identity_pb_identity_proto_goTypes = nil
	file_internal_identity_pb_identity_proto_depIdxs = nil
}
